#!/bin/sh
# Generated by Vaio Panel. This file includes a single-use credential (expires in 30 minutes).
set -eu
umask 077
[ "$(id -u)" = 0 ] || { echo '请使用 root 执行此安装脚本'; exit 1; }
PANEL_URL=@@URL@@
if command -v apt-get >/dev/null 2>&1; then
  apt-get update -qq
  DEBIAN_FRONTEND=noninteractive apt-get install -y python3 bash curl ca-certificates tar jq openssl unzip util-linux nftables
elif command -v apk >/dev/null 2>&1; then
  apk add --no-cache python3 bash curl ca-certificates tar jq openssl unzip util-linux nftables
elif command -v dnf >/dev/null 2>&1; then
  dnf install -y python3 bash curl ca-certificates tar jq openssl unzip util-linux nftables
else
  echo '首版支持 Debian/Ubuntu、Alpine 和提供 dnf 的发行版'; exit 1
fi
python3 -c 'import sys; assert sys.version_info >= (3,9), "需要 Python 3.9+"'
WORK=$(mktemp -d)
trap 'rm -rf "$WORK"' EXIT HUP INT TERM
curl --fail --silent --show-error --max-time 180 "$PANEL_URL/downloads/agent.tar.gz" -o "$WORK/agent.tar.gz"
curl --fail --silent --show-error --max-time 30 "$PANEL_URL/downloads/agent.sha256" -o "$WORK/agent.sha256"
(cd "$WORK" && sha256sum -c agent.sha256)
mkdir -p /opt/vaio-agent /etc/vaio-agent /var/lib/vaio-agent
chmod 700 /etc/vaio-agent /var/lib/vaio-agent
# Stop only the Agent during replacement. Proxy services continue independently.
if command -v systemctl >/dev/null 2>&1; then systemctl stop vaio-agent 2>/dev/null || true
elif command -v rc-service >/dev/null 2>&1; then rc-service vaio-agent stop 2>/dev/null || true; fi
tar -xzf "$WORK/agent.tar.gz" -C /opt/vaio-agent --no-same-owner
cd /opt/vaio-agent
python3 -m agent enroll <<'VAIO_ENROLLMENT'
@@ENROLLMENT@@
VAIO_ENROLLMENT
if command -v systemctl >/dev/null 2>&1; then
  cat > /etc/systemd/system/vaio-agent.service <<'UNIT'
[Unit]
Description=Vaio Panel node agent
After=network-online.target
Wants=network-online.target
[Service]
Type=simple
WorkingDirectory=/opt/vaio-agent
ExecStart=/usr/bin/python3 -m agent run
Restart=always
RestartSec=10
UMask=0077
[Install]
WantedBy=multi-user.target
UNIT
  systemctl daemon-reload
  systemctl enable --now vaio-agent
elif command -v rc-service >/dev/null 2>&1; then
  cat > /etc/init.d/vaio-agent <<'UNIT'
#!/sbin/openrc-run
name="Vaio Agent"
supervisor="supervise-daemon"
directory="/opt/vaio-agent"
command="/usr/bin/python3"
command_args="-m agent run"
respawn_delay=10
output_log="/var/lib/vaio-agent/agent.log"
error_log="/var/lib/vaio-agent/agent.log"
depend() { need net; }
UNIT
  chmod 755 /etc/init.d/vaio-agent
  rc-update add vaio-agent default
  rc-service vaio-agent start
else
  echo '未找到 systemd/OpenRC，请在 /opt/vaio-agent 手动运行 python3 -m agent run'; exit 1
fi
echo 'Agent 已启动。返回面板查看节点并确认接管；请删除此安装脚本。'
